images-students-path: "C:/escolaPro/images-students"
files-students-path: "C:/escolaPro/files-students"
files-family-path: "C:/escolaPro/files-family"
files-financialResponsible-path: "C:/escolaPro/files-financialResponsible"

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
